# -*- coding: utf-8 -*-
"""First Assignment AIML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xSZHPLTCNXRpIGBClSZbX3aP0M2AT1-V
"""

import pandas as pd
import numpy as np


rows = 4
columns = 4
random_data = np.random.randint(0,101, size = (rows, columns))

df = pd.DataFrame(random_data, columns=['Age', 'Height', 'Weight', 'IQ'])

print(df)



col_names = ["Random Value 1","Random Value 2","Random Value 3","Randome Value 4"]
df.columns = col_names
print(df)

df.describe()

df.isnull().any()

df.info()

df2 = df.loc[:,["Random Value 2","Random Value 3"]]
print(df2)
df3 = df.iloc[:,[1,2]]
print(df3)

rows = 10
columns = 5
data = np.random.randint(0,101,size=(rows,columns))
df = pd.DataFrame(data, columns=['Age', 'Height', 'Weight', 'IQ','Shoe size'])
print(df)

df.info()

df.describe()

df2 = df.loc[4]
print(df2)

df.isnull().any()